package com.btc.mapper;

import java.util.List;
import java.util.Map;

import com.btc.model.CoinRecord;

public interface CoinRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_coin_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_coin_record
     *
     * @mbggenerated
     */
    int insert(CoinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_coin_record
     *
     * @mbggenerated
     */
    int insertSelective(CoinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_coin_record
     *
     * @mbggenerated
     */
    CoinRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_coin_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_coin_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoinRecord record);
    
    
    List<CoinRecord> queryCoinRecord(Map<String,Object> map);
    
    int getCoinRecordCount(Map<String,Object> map);
    
    
    
}