package com.btc.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.btc.model.UserIncomeVerifyTemp;

public interface UserIncomeVerifyTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify_temp
     *
     * @mbggenerated
     */
    int insert(UserIncomeVerifyTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify_temp
     *
     * @mbggenerated
     */
    int insertSelective(UserIncomeVerifyTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify_temp
     *
     * @mbggenerated
     */
    UserIncomeVerifyTemp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserIncomeVerifyTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserIncomeVerifyTemp record);
    
    
    
    List<UserIncomeVerifyTemp>  queryUserIncomeVerifyTempRecord(Map<String,Object> params);
    
    @Select("SELECT * FROM btc_user_income_verify_temp")
    @ResultMap("BaseResultMap")
    List<UserIncomeVerifyTemp> getAll();
    
    int getUserIncomeVerifyRecordTempCount(Map<String,Object> params);
    
    @Delete("TRUNCATE btc_user_income_verify_temp")
    void truncateUserIncomeVerifyTemp();
    
    void batchInsert(@Param("list") List<UserIncomeVerifyTemp> list);
    
    @Select("SELECT COUNT(1) FROM btc_user_income_verify_temp t WHERE DATE(t.count_date)=DATE(#{arg1}) ")
    int getUserIncomeVerifyTempCount(Date date);
}