package com.btc.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;

import com.btc.model.UserIncomeVerify;
import com.btc.model.UserIncomeVerifyTemp;

public interface UserIncomeVerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify
     *
     * @mbggenerated
     */
    int insert(UserIncomeVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify
     *
     * @mbggenerated
     */
    int insertSelective(UserIncomeVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify
     *
     * @mbggenerated
     */
    UserIncomeVerify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserIncomeVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_user_income_verify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserIncomeVerify record);
    
    
    List<UserIncomeVerify> queryUserIncomeVerifyRecord(Map<String,Object> params);
    
    
    int  getUserIncomeVerifyRecordCount(Map<String,Object> params);
    
    @Delete("DELETE t FROM btc_user_income_verify t WHERE DATE(t.count_date)=DATE(#{arg0})")
    void delUserIncomeVerifyByDate(Date date);
    
    
    void batchInsert(@Param("list") List<UserIncomeVerify> list);
}