package com.btc.model.admin;

import java.math.BigDecimal;
import java.util.Date;

public class SysCoinsDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.coin_code
     *
     * @mbggenerated
     */
    private String coinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.coin_icon
     *
     * @mbggenerated
     */
    private String coinIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.coin_color
     *
     * @mbggenerated
     */
    private String coinColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.min_income_count
     *
     * @mbggenerated
     */
    private BigDecimal minIncomeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.min_turn_in_count
     *
     * @mbggenerated
     */
    private BigDecimal minTurnInCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.min_turn_out_count
     *
     * @mbggenerated
     */
    private BigDecimal minTurnOutCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.is_del
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_coins_dic.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.id
     *
     * @return the value of sys_coins_dic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.id
     *
     * @param id the value for sys_coins_dic.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.coin_code
     *
     * @return the value of sys_coins_dic.coin_code
     *
     * @mbggenerated
     */
    public String getCoinCode() {
        return coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.coin_code
     *
     * @param coinCode the value for sys_coins_dic.coin_code
     *
     * @mbggenerated
     */
    public void setCoinCode(String coinCode) {
        this.coinCode = coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.coin_icon
     *
     * @return the value of sys_coins_dic.coin_icon
     *
     * @mbggenerated
     */
    public String getCoinIcon() {
        return coinIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.coin_icon
     *
     * @param coinIcon the value for sys_coins_dic.coin_icon
     *
     * @mbggenerated
     */
    public void setCoinIcon(String coinIcon) {
        this.coinIcon = coinIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.coin_color
     *
     * @return the value of sys_coins_dic.coin_color
     *
     * @mbggenerated
     */
    public String getCoinColor() {
        return coinColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.coin_color
     *
     * @param coinColor the value for sys_coins_dic.coin_color
     *
     * @mbggenerated
     */
    public void setCoinColor(String coinColor) {
        this.coinColor = coinColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.min_income_count
     *
     * @return the value of sys_coins_dic.min_income_count
     *
     * @mbggenerated
     */
    public BigDecimal getMinIncomeCount() {
        return minIncomeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.min_income_count
     *
     * @param minIncomeCount the value for sys_coins_dic.min_income_count
     *
     * @mbggenerated
     */
    public void setMinIncomeCount(BigDecimal minIncomeCount) {
        this.minIncomeCount = minIncomeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.min_turn_in_count
     *
     * @return the value of sys_coins_dic.min_turn_in_count
     *
     * @mbggenerated
     */
    public BigDecimal getMinTurnInCount() {
        return minTurnInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.min_turn_in_count
     *
     * @param minTurnInCount the value for sys_coins_dic.min_turn_in_count
     *
     * @mbggenerated
     */
    public void setMinTurnInCount(BigDecimal minTurnInCount) {
        this.minTurnInCount = minTurnInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.min_turn_out_count
     *
     * @return the value of sys_coins_dic.min_turn_out_count
     *
     * @mbggenerated
     */
    public BigDecimal getMinTurnOutCount() {
        return minTurnOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.min_turn_out_count
     *
     * @param minTurnOutCount the value for sys_coins_dic.min_turn_out_count
     *
     * @mbggenerated
     */
    public void setMinTurnOutCount(BigDecimal minTurnOutCount) {
        this.minTurnOutCount = minTurnOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.is_del
     *
     * @return the value of sys_coins_dic.is_del
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.is_del
     *
     * @param isDel the value for sys_coins_dic.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.status
     *
     * @return the value of sys_coins_dic.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.status
     *
     * @param status the value for sys_coins_dic.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_coins_dic.gmt_create
     *
     * @return the value of sys_coins_dic.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_coins_dic.gmt_create
     *
     * @param gmtCreate the value for sys_coins_dic.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}