package com.btc.model.admin;

import java.util.Date;

public class SystemSecondItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.first_id
     *
     * @mbggenerated
     */
    private Long firstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.order_index
     *
     * @mbggenerated
     */
    private Integer orderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_second_item.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.id
     *
     * @return the value of system_second_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.id
     *
     * @param id the value for system_second_item.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.first_id
     *
     * @return the value of system_second_item.first_id
     *
     * @mbggenerated
     */
    public Long getFirstId() {
        return firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.first_id
     *
     * @param firstId the value for system_second_item.first_id
     *
     * @mbggenerated
     */
    public void setFirstId(Long firstId) {
        this.firstId = firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.url
     *
     * @return the value of system_second_item.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.url
     *
     * @param url the value for system_second_item.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.item_name
     *
     * @return the value of system_second_item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.item_name
     *
     * @param itemName the value for system_second_item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.status
     *
     * @return the value of system_second_item.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.status
     *
     * @param status the value for system_second_item.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.order_index
     *
     * @return the value of system_second_item.order_index
     *
     * @mbggenerated
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.order_index
     *
     * @param orderIndex the value for system_second_item.order_index
     *
     * @mbggenerated
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.level
     *
     * @return the value of system_second_item.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.level
     *
     * @param level the value for system_second_item.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_second_item.create_date
     *
     * @return the value of system_second_item.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_second_item.create_date
     *
     * @param createDate the value for system_second_item.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
}