package com.btc.model.admin;

public class UUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.first_item_id
     *
     * @mbggenerated
     */
    private Long firstItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.second_item_id
     *
     * @mbggenerated
     */
    private Long secondItemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.user_id
     *
     * @return the value of u_user_role.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.user_id
     *
     * @param userId the value for u_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.first_item_id
     *
     * @return the value of u_user_role.first_item_id
     *
     * @mbggenerated
     */
    public Long getFirstItemId() {
        return firstItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.first_item_id
     *
     * @param firstItemId the value for u_user_role.first_item_id
     *
     * @mbggenerated
     */
    public void setFirstItemId(Long firstItemId) {
        this.firstItemId = firstItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.second_item_id
     *
     * @return the value of u_user_role.second_item_id
     *
     * @mbggenerated
     */
    public Long getSecondItemId() {
        return secondItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.second_item_id
     *
     * @param secondItemId the value for u_user_role.second_item_id
     *
     * @mbggenerated
     */
    public void setSecondItemId(Long secondItemId) {
        this.secondItemId = secondItemId;
    }
}