package com.btc.mapper.admin;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.btc.model.admin.SysCoinsDic;

public interface SysCoinsDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coins_dic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coins_dic
     *
     * @mbggenerated
     */
    int insert(SysCoinsDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coins_dic
     *
     * @mbggenerated
     */
    int insertSelective(SysCoinsDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coins_dic
     *
     * @mbggenerated
     */
    SysCoinsDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coins_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysCoinsDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_coins_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCoinsDic record);
    
    
    List<SysCoinsDic> querySysCoinsDic(Map<String,Object> map);
    
    int getSysCoinsCount(Map<String,Object> map);
    
    void setIsDel(long dicId);
    
    @Select("SELECT count(1)>0 FROM sys_coins_dic t WHERE t.coin_code=#{arg0}")
    public boolean checkCoinsCodeIsExist(String coinCode);
    
    
    @Select("SELECT * FROM sys_coins_dic t WHERE t.coin_code=#{arg0}")
    @ResultMap("BaseResultMap")
    public SysCoinsDic getCoinsCodeDicByCode(String coinCode);
    
    @Select("SELECT * FROM sys_coins_dic t WHERE t.status=1 AND t.is_del=0 ORDER BY t.coin_code ASC")
    @ResultMap("BaseResultMap")
    public List<SysCoinsDic> queryAllCoins();
    
    @Update("UPDATE btc_coin_rate_record t SET t.usdt_unit=#{arg0} WHERE t.coin_code=#{arg1} AND DATE(t.apply_date)=DATE(#{arg2})")
    void updateCoinUSDT(BigDecimal usdt,String coinCode,Date date);
}