package com.btc.mapper.admin;

import java.util.List;

import net.paoding.rose.web.annotation.Param;

import com.btc.model.admin.UUserRole;

public interface UUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbggenerated
     */
    int insert(UUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbggenerated
     */
    int insertSelective(UUserRole record);
    
    
    List<UUserRole> queryUserRole(int userId);
    
    
    int batchInsert(@Param("list") List<UUserRole> list);
    
    
    int deleteUserRole(long userId);
}