package com.btc.model;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class CoinRateRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.coin_code
     *
     * @mbggenerated
     */
    private String coinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.coin_day_rate
     *
     * @mbggenerated
     */
    private BigDecimal coinDayRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.coin_year_rate
     *
     * @mbggenerated
     */
    private BigDecimal coinYearRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_coin_rate_record.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_coin_rate_record.id
     *
     * @return the value of btc_coin_rate_record.id
     *
     * @mbggenerated
     * 
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date applyDate;
    private String beginDate;
    
    private String endDate;
    
    private BigDecimal usdtUnit;

    
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_coin_rate_record.id
     *
     * @param id the value for btc_coin_rate_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_coin_rate_record.coin_code
     *
     * @return the value of btc_coin_rate_record.coin_code
     *
     * @mbggenerated
     */
    public String getCoinCode() {
        return coinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_coin_rate_record.coin_code
     *
     * @param coinCode the value for btc_coin_rate_record.coin_code
     *
     * @mbggenerated
     */
    public void setCoinCode(String coinCode) {
        this.coinCode = coinCode;
    }

    
    public BigDecimal getCoinDayRate() {
		return coinDayRate;
	}

	public void setCoinDayRate(BigDecimal coinDayRate) {
		this.coinDayRate = coinDayRate;
	}

	public BigDecimal getCoinYearRate() {
		return coinYearRate;
	}

	public void setCoinYearRate(BigDecimal coinYearRate) {
		this.coinYearRate = coinYearRate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_coin_rate_record.status
     *
     * @return the value of btc_coin_rate_record.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_coin_rate_record.status
     *
     * @param status the value for btc_coin_rate_record.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_coin_rate_record.gmt_create
     *
     * @return the value of btc_coin_rate_record.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_coin_rate_record.gmt_create
     *
     * @param gmtCreate the value for btc_coin_rate_record.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_coin_rate_record.gmt_modify
     *
     * @return the value of btc_coin_rate_record.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_coin_rate_record.gmt_modify
     *
     * @param gmtModify the value for btc_coin_rate_record.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

	public String getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Date getApplyDate() {
		return applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public BigDecimal getUsdtUnit() {
		return usdtUnit;
	}

	public void setUsdtUnit(BigDecimal usdtUnit) {
		this.usdtUnit = usdtUnit;
	}

    
}